name: Build Flutter APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unzip
        run: |
          unzip -o Hello-world.zip -d project_dir
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Build
        run: |
          cd project_dir
          flutter pub get
          flutter build apk --release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: project_dir/**/build/app/outputs/flutter-apk/app-release.apk
          
